# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='project_title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
