# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-02 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draken', '0002_auto_20170702_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
