# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 14:04
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('draken', '0003_auto_20170702_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
